/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentHistoryRouteImport } from './routes/api/agent/history'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHistoryRoute = ApiAgentHistoryRouteImport.update({
  id: '/api/agent/history',
  path: '/api/agent/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent/chat',
  path: '/api/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/agent/chat' | '/api/agent/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agent/chat' | '/api/agent/history'
  id: '__root__' | '/' | '/api/agent/chat' | '/api/agent/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiAgentHistoryRoute: typeof ApiAgentHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/history': {
      id: '/api/agent/history'
      path: '/api/agent/history'
      fullPath: '/api/agent/history'
      preLoaderRoute: typeof ApiAgentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/chat': {
      id: '/api/agent/chat'
      path: '/api/agent/chat'
      fullPath: '/api/agent/chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiAgentHistoryRoute: ApiAgentHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
