/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiModelingWorkspacesRouteImport } from './routes/api/modeling/workspaces'
import { Route as ApiModelingTranslationsRouteImport } from './routes/api/modeling/translations'
import { Route as ApiModelingDocumentsRouteImport } from './routes/api/modeling/documents'
import { Route as ApiModelingDocumentRecordsRouteImport } from './routes/api/modeling/document-records'
import { Route as ApiModelingDocumentExportRouteImport } from './routes/api/modeling/document-export'
import { Route as ApiModelingCodegenModelRouteImport } from './routes/api/modeling/codegen-model'
import { Route as ApiAgentSliceStatusesRouteImport } from './routes/api/agent/slice-statuses'
import { Route as ApiAgentHistoryRouteImport } from './routes/api/agent/history'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent/chat'
import { Route as ApiModelingWorkspacesWorkspaceIdRouteImport } from './routes/api/modeling/workspaces.$workspaceId'
import { Route as ApiModelingDocumentRecordsDocumentIdRouteImport } from './routes/api/modeling/document-records.$documentId'
import { Route as ApiModelingWorkspacesWorkspaceIdVersionsRouteImport } from './routes/api/modeling/workspaces.$workspaceId.versions'
import { Route as ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRouteImport } from './routes/api/modeling/workspaces.$workspaceId.versions.$versionId'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingWorkspacesRoute = ApiModelingWorkspacesRouteImport.update({
  id: '/api/modeling/workspaces',
  path: '/api/modeling/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingTranslationsRoute = ApiModelingTranslationsRouteImport.update({
  id: '/api/modeling/translations',
  path: '/api/modeling/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingDocumentsRoute = ApiModelingDocumentsRouteImport.update({
  id: '/api/modeling/documents',
  path: '/api/modeling/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingDocumentRecordsRoute =
  ApiModelingDocumentRecordsRouteImport.update({
    id: '/api/modeling/document-records',
    path: '/api/modeling/document-records',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiModelingDocumentExportRoute =
  ApiModelingDocumentExportRouteImport.update({
    id: '/api/modeling/document-export',
    path: '/api/modeling/document-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiModelingCodegenModelRoute = ApiModelingCodegenModelRouteImport.update({
  id: '/api/modeling/codegen-model',
  path: '/api/modeling/codegen-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSliceStatusesRoute = ApiAgentSliceStatusesRouteImport.update({
  id: '/api/agent/slice-statuses',
  path: '/api/agent/slice-statuses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHistoryRoute = ApiAgentHistoryRouteImport.update({
  id: '/api/agent/history',
  path: '/api/agent/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent/chat',
  path: '/api/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingWorkspacesWorkspaceIdRoute =
  ApiModelingWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ApiModelingWorkspacesRoute,
  } as any)
const ApiModelingDocumentRecordsDocumentIdRoute =
  ApiModelingDocumentRecordsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ApiModelingDocumentRecordsRoute,
  } as any)
const ApiModelingWorkspacesWorkspaceIdVersionsRoute =
  ApiModelingWorkspacesWorkspaceIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ApiModelingWorkspacesWorkspaceIdRoute,
  } as any)
const ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute =
  ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => ApiModelingWorkspacesWorkspaceIdVersionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/preview': typeof PreviewRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
  '/api/agent/slice-statuses': typeof ApiAgentSliceStatusesRoute
  '/api/modeling/codegen-model': typeof ApiModelingCodegenModelRoute
  '/api/modeling/document-export': typeof ApiModelingDocumentExportRoute
  '/api/modeling/document-records': typeof ApiModelingDocumentRecordsRouteWithChildren
  '/api/modeling/documents': typeof ApiModelingDocumentsRoute
  '/api/modeling/translations': typeof ApiModelingTranslationsRoute
  '/api/modeling/workspaces': typeof ApiModelingWorkspacesRouteWithChildren
  '/api/modeling/document-records/$documentId': typeof ApiModelingDocumentRecordsDocumentIdRoute
  '/api/modeling/workspaces/$workspaceId': typeof ApiModelingWorkspacesWorkspaceIdRouteWithChildren
  '/api/modeling/workspaces/$workspaceId/versions': typeof ApiModelingWorkspacesWorkspaceIdVersionsRouteWithChildren
  '/api/modeling/workspaces/$workspaceId/versions/$versionId': typeof ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/preview': typeof PreviewRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
  '/api/agent/slice-statuses': typeof ApiAgentSliceStatusesRoute
  '/api/modeling/codegen-model': typeof ApiModelingCodegenModelRoute
  '/api/modeling/document-export': typeof ApiModelingDocumentExportRoute
  '/api/modeling/document-records': typeof ApiModelingDocumentRecordsRouteWithChildren
  '/api/modeling/documents': typeof ApiModelingDocumentsRoute
  '/api/modeling/translations': typeof ApiModelingTranslationsRoute
  '/api/modeling/workspaces': typeof ApiModelingWorkspacesRouteWithChildren
  '/api/modeling/document-records/$documentId': typeof ApiModelingDocumentRecordsDocumentIdRoute
  '/api/modeling/workspaces/$workspaceId': typeof ApiModelingWorkspacesWorkspaceIdRouteWithChildren
  '/api/modeling/workspaces/$workspaceId/versions': typeof ApiModelingWorkspacesWorkspaceIdVersionsRouteWithChildren
  '/api/modeling/workspaces/$workspaceId/versions/$versionId': typeof ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/preview': typeof PreviewRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
  '/api/agent/slice-statuses': typeof ApiAgentSliceStatusesRoute
  '/api/modeling/codegen-model': typeof ApiModelingCodegenModelRoute
  '/api/modeling/document-export': typeof ApiModelingDocumentExportRoute
  '/api/modeling/document-records': typeof ApiModelingDocumentRecordsRouteWithChildren
  '/api/modeling/documents': typeof ApiModelingDocumentsRoute
  '/api/modeling/translations': typeof ApiModelingTranslationsRoute
  '/api/modeling/workspaces': typeof ApiModelingWorkspacesRouteWithChildren
  '/api/modeling/document-records/$documentId': typeof ApiModelingDocumentRecordsDocumentIdRoute
  '/api/modeling/workspaces/$workspaceId': typeof ApiModelingWorkspacesWorkspaceIdRouteWithChildren
  '/api/modeling/workspaces/$workspaceId/versions': typeof ApiModelingWorkspacesWorkspaceIdVersionsRouteWithChildren
  '/api/modeling/workspaces/$workspaceId/versions/$versionId': typeof ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/preview'
    | '/api/agent/chat'
    | '/api/agent/history'
    | '/api/agent/slice-statuses'
    | '/api/modeling/codegen-model'
    | '/api/modeling/document-export'
    | '/api/modeling/document-records'
    | '/api/modeling/documents'
    | '/api/modeling/translations'
    | '/api/modeling/workspaces'
    | '/api/modeling/document-records/$documentId'
    | '/api/modeling/workspaces/$workspaceId'
    | '/api/modeling/workspaces/$workspaceId/versions'
    | '/api/modeling/workspaces/$workspaceId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/preview'
    | '/api/agent/chat'
    | '/api/agent/history'
    | '/api/agent/slice-statuses'
    | '/api/modeling/codegen-model'
    | '/api/modeling/document-export'
    | '/api/modeling/document-records'
    | '/api/modeling/documents'
    | '/api/modeling/translations'
    | '/api/modeling/workspaces'
    | '/api/modeling/document-records/$documentId'
    | '/api/modeling/workspaces/$workspaceId'
    | '/api/modeling/workspaces/$workspaceId/versions'
    | '/api/modeling/workspaces/$workspaceId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/preview'
    | '/api/agent/chat'
    | '/api/agent/history'
    | '/api/agent/slice-statuses'
    | '/api/modeling/codegen-model'
    | '/api/modeling/document-export'
    | '/api/modeling/document-records'
    | '/api/modeling/documents'
    | '/api/modeling/translations'
    | '/api/modeling/workspaces'
    | '/api/modeling/document-records/$documentId'
    | '/api/modeling/workspaces/$workspaceId'
    | '/api/modeling/workspaces/$workspaceId/versions'
    | '/api/modeling/workspaces/$workspaceId/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  PreviewRoute: typeof PreviewRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiAgentHistoryRoute: typeof ApiAgentHistoryRoute
  ApiAgentSliceStatusesRoute: typeof ApiAgentSliceStatusesRoute
  ApiModelingCodegenModelRoute: typeof ApiModelingCodegenModelRoute
  ApiModelingDocumentExportRoute: typeof ApiModelingDocumentExportRoute
  ApiModelingDocumentRecordsRoute: typeof ApiModelingDocumentRecordsRouteWithChildren
  ApiModelingDocumentsRoute: typeof ApiModelingDocumentsRoute
  ApiModelingTranslationsRoute: typeof ApiModelingTranslationsRoute
  ApiModelingWorkspacesRoute: typeof ApiModelingWorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/workspaces': {
      id: '/api/modeling/workspaces'
      path: '/api/modeling/workspaces'
      fullPath: '/api/modeling/workspaces'
      preLoaderRoute: typeof ApiModelingWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/translations': {
      id: '/api/modeling/translations'
      path: '/api/modeling/translations'
      fullPath: '/api/modeling/translations'
      preLoaderRoute: typeof ApiModelingTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/documents': {
      id: '/api/modeling/documents'
      path: '/api/modeling/documents'
      fullPath: '/api/modeling/documents'
      preLoaderRoute: typeof ApiModelingDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/document-records': {
      id: '/api/modeling/document-records'
      path: '/api/modeling/document-records'
      fullPath: '/api/modeling/document-records'
      preLoaderRoute: typeof ApiModelingDocumentRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/document-export': {
      id: '/api/modeling/document-export'
      path: '/api/modeling/document-export'
      fullPath: '/api/modeling/document-export'
      preLoaderRoute: typeof ApiModelingDocumentExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/codegen-model': {
      id: '/api/modeling/codegen-model'
      path: '/api/modeling/codegen-model'
      fullPath: '/api/modeling/codegen-model'
      preLoaderRoute: typeof ApiModelingCodegenModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/slice-statuses': {
      id: '/api/agent/slice-statuses'
      path: '/api/agent/slice-statuses'
      fullPath: '/api/agent/slice-statuses'
      preLoaderRoute: typeof ApiAgentSliceStatusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/history': {
      id: '/api/agent/history'
      path: '/api/agent/history'
      fullPath: '/api/agent/history'
      preLoaderRoute: typeof ApiAgentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/chat': {
      id: '/api/agent/chat'
      path: '/api/agent/chat'
      fullPath: '/api/agent/chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/workspaces/$workspaceId': {
      id: '/api/modeling/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/api/modeling/workspaces/$workspaceId'
      preLoaderRoute: typeof ApiModelingWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ApiModelingWorkspacesRoute
    }
    '/api/modeling/document-records/$documentId': {
      id: '/api/modeling/document-records/$documentId'
      path: '/$documentId'
      fullPath: '/api/modeling/document-records/$documentId'
      preLoaderRoute: typeof ApiModelingDocumentRecordsDocumentIdRouteImport
      parentRoute: typeof ApiModelingDocumentRecordsRoute
    }
    '/api/modeling/workspaces/$workspaceId/versions': {
      id: '/api/modeling/workspaces/$workspaceId/versions'
      path: '/versions'
      fullPath: '/api/modeling/workspaces/$workspaceId/versions'
      preLoaderRoute: typeof ApiModelingWorkspacesWorkspaceIdVersionsRouteImport
      parentRoute: typeof ApiModelingWorkspacesWorkspaceIdRoute
    }
    '/api/modeling/workspaces/$workspaceId/versions/$versionId': {
      id: '/api/modeling/workspaces/$workspaceId/versions/$versionId'
      path: '/$versionId'
      fullPath: '/api/modeling/workspaces/$workspaceId/versions/$versionId'
      preLoaderRoute: typeof ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRouteImport
      parentRoute: typeof ApiModelingWorkspacesWorkspaceIdVersionsRoute
    }
  }
}

interface ApiModelingDocumentRecordsRouteChildren {
  ApiModelingDocumentRecordsDocumentIdRoute: typeof ApiModelingDocumentRecordsDocumentIdRoute
}

const ApiModelingDocumentRecordsRouteChildren: ApiModelingDocumentRecordsRouteChildren =
  {
    ApiModelingDocumentRecordsDocumentIdRoute:
      ApiModelingDocumentRecordsDocumentIdRoute,
  }

const ApiModelingDocumentRecordsRouteWithChildren =
  ApiModelingDocumentRecordsRoute._addFileChildren(
    ApiModelingDocumentRecordsRouteChildren,
  )

interface ApiModelingWorkspacesWorkspaceIdVersionsRouteChildren {
  ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute: typeof ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute
}

const ApiModelingWorkspacesWorkspaceIdVersionsRouteChildren: ApiModelingWorkspacesWorkspaceIdVersionsRouteChildren =
  {
    ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute:
      ApiModelingWorkspacesWorkspaceIdVersionsVersionIdRoute,
  }

const ApiModelingWorkspacesWorkspaceIdVersionsRouteWithChildren =
  ApiModelingWorkspacesWorkspaceIdVersionsRoute._addFileChildren(
    ApiModelingWorkspacesWorkspaceIdVersionsRouteChildren,
  )

interface ApiModelingWorkspacesWorkspaceIdRouteChildren {
  ApiModelingWorkspacesWorkspaceIdVersionsRoute: typeof ApiModelingWorkspacesWorkspaceIdVersionsRouteWithChildren
}

const ApiModelingWorkspacesWorkspaceIdRouteChildren: ApiModelingWorkspacesWorkspaceIdRouteChildren =
  {
    ApiModelingWorkspacesWorkspaceIdVersionsRoute:
      ApiModelingWorkspacesWorkspaceIdVersionsRouteWithChildren,
  }

const ApiModelingWorkspacesWorkspaceIdRouteWithChildren =
  ApiModelingWorkspacesWorkspaceIdRoute._addFileChildren(
    ApiModelingWorkspacesWorkspaceIdRouteChildren,
  )

interface ApiModelingWorkspacesRouteChildren {
  ApiModelingWorkspacesWorkspaceIdRoute: typeof ApiModelingWorkspacesWorkspaceIdRouteWithChildren
}

const ApiModelingWorkspacesRouteChildren: ApiModelingWorkspacesRouteChildren = {
  ApiModelingWorkspacesWorkspaceIdRoute:
    ApiModelingWorkspacesWorkspaceIdRouteWithChildren,
}

const ApiModelingWorkspacesRouteWithChildren =
  ApiModelingWorkspacesRoute._addFileChildren(
    ApiModelingWorkspacesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  PreviewRoute: PreviewRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiAgentHistoryRoute: ApiAgentHistoryRoute,
  ApiAgentSliceStatusesRoute: ApiAgentSliceStatusesRoute,
  ApiModelingCodegenModelRoute: ApiModelingCodegenModelRoute,
  ApiModelingDocumentExportRoute: ApiModelingDocumentExportRoute,
  ApiModelingDocumentRecordsRoute: ApiModelingDocumentRecordsRouteWithChildren,
  ApiModelingDocumentsRoute: ApiModelingDocumentsRoute,
  ApiModelingTranslationsRoute: ApiModelingTranslationsRoute,
  ApiModelingWorkspacesRoute: ApiModelingWorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
