/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiModelingWorkspacesRouteImport } from './routes/api/modeling/workspaces'
import { Route as ApiModelingDocumentsRouteImport } from './routes/api/modeling/documents'
import { Route as ApiModelingDocumentRecordsRouteImport } from './routes/api/modeling/document-records'
import { Route as ApiAgentHistoryRouteImport } from './routes/api/agent/history'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent/chat'
import { Route as ApiModelingWorkspacesWorkspaceIdRouteImport } from './routes/api/modeling/workspaces.$workspaceId'
import { Route as ApiModelingDocumentRecordsDocumentIdRouteImport } from './routes/api/modeling/document-records.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingWorkspacesRoute = ApiModelingWorkspacesRouteImport.update({
  id: '/api/modeling/workspaces',
  path: '/api/modeling/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingDocumentsRoute = ApiModelingDocumentsRouteImport.update({
  id: '/api/modeling/documents',
  path: '/api/modeling/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingDocumentRecordsRoute =
  ApiModelingDocumentRecordsRouteImport.update({
    id: '/api/modeling/document-records',
    path: '/api/modeling/document-records',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentHistoryRoute = ApiAgentHistoryRouteImport.update({
  id: '/api/agent/history',
  path: '/api/agent/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent/chat',
  path: '/api/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelingWorkspacesWorkspaceIdRoute =
  ApiModelingWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ApiModelingWorkspacesRoute,
  } as any)
const ApiModelingDocumentRecordsDocumentIdRoute =
  ApiModelingDocumentRecordsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ApiModelingDocumentRecordsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
  '/api/modeling/document-records': typeof ApiModelingDocumentRecordsRouteWithChildren
  '/api/modeling/documents': typeof ApiModelingDocumentsRoute
  '/api/modeling/workspaces': typeof ApiModelingWorkspacesRouteWithChildren
  '/api/modeling/document-records/$documentId': typeof ApiModelingDocumentRecordsDocumentIdRoute
  '/api/modeling/workspaces/$workspaceId': typeof ApiModelingWorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
  '/api/modeling/document-records': typeof ApiModelingDocumentRecordsRouteWithChildren
  '/api/modeling/documents': typeof ApiModelingDocumentsRoute
  '/api/modeling/workspaces': typeof ApiModelingWorkspacesRouteWithChildren
  '/api/modeling/document-records/$documentId': typeof ApiModelingDocumentRecordsDocumentIdRoute
  '/api/modeling/workspaces/$workspaceId': typeof ApiModelingWorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent/chat': typeof ApiAgentChatRoute
  '/api/agent/history': typeof ApiAgentHistoryRoute
  '/api/modeling/document-records': typeof ApiModelingDocumentRecordsRouteWithChildren
  '/api/modeling/documents': typeof ApiModelingDocumentsRoute
  '/api/modeling/workspaces': typeof ApiModelingWorkspacesRouteWithChildren
  '/api/modeling/document-records/$documentId': typeof ApiModelingDocumentRecordsDocumentIdRoute
  '/api/modeling/workspaces/$workspaceId': typeof ApiModelingWorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent/chat'
    | '/api/agent/history'
    | '/api/modeling/document-records'
    | '/api/modeling/documents'
    | '/api/modeling/workspaces'
    | '/api/modeling/document-records/$documentId'
    | '/api/modeling/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent/chat'
    | '/api/agent/history'
    | '/api/modeling/document-records'
    | '/api/modeling/documents'
    | '/api/modeling/workspaces'
    | '/api/modeling/document-records/$documentId'
    | '/api/modeling/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/api/agent/chat'
    | '/api/agent/history'
    | '/api/modeling/document-records'
    | '/api/modeling/documents'
    | '/api/modeling/workspaces'
    | '/api/modeling/document-records/$documentId'
    | '/api/modeling/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiAgentHistoryRoute: typeof ApiAgentHistoryRoute
  ApiModelingDocumentRecordsRoute: typeof ApiModelingDocumentRecordsRouteWithChildren
  ApiModelingDocumentsRoute: typeof ApiModelingDocumentsRoute
  ApiModelingWorkspacesRoute: typeof ApiModelingWorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/workspaces': {
      id: '/api/modeling/workspaces'
      path: '/api/modeling/workspaces'
      fullPath: '/api/modeling/workspaces'
      preLoaderRoute: typeof ApiModelingWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/documents': {
      id: '/api/modeling/documents'
      path: '/api/modeling/documents'
      fullPath: '/api/modeling/documents'
      preLoaderRoute: typeof ApiModelingDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/document-records': {
      id: '/api/modeling/document-records'
      path: '/api/modeling/document-records'
      fullPath: '/api/modeling/document-records'
      preLoaderRoute: typeof ApiModelingDocumentRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/history': {
      id: '/api/agent/history'
      path: '/api/agent/history'
      fullPath: '/api/agent/history'
      preLoaderRoute: typeof ApiAgentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/chat': {
      id: '/api/agent/chat'
      path: '/api/agent/chat'
      fullPath: '/api/agent/chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modeling/workspaces/$workspaceId': {
      id: '/api/modeling/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/api/modeling/workspaces/$workspaceId'
      preLoaderRoute: typeof ApiModelingWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ApiModelingWorkspacesRoute
    }
    '/api/modeling/document-records/$documentId': {
      id: '/api/modeling/document-records/$documentId'
      path: '/$documentId'
      fullPath: '/api/modeling/document-records/$documentId'
      preLoaderRoute: typeof ApiModelingDocumentRecordsDocumentIdRouteImport
      parentRoute: typeof ApiModelingDocumentRecordsRoute
    }
  }
}

interface ApiModelingDocumentRecordsRouteChildren {
  ApiModelingDocumentRecordsDocumentIdRoute: typeof ApiModelingDocumentRecordsDocumentIdRoute
}

const ApiModelingDocumentRecordsRouteChildren: ApiModelingDocumentRecordsRouteChildren =
  {
    ApiModelingDocumentRecordsDocumentIdRoute:
      ApiModelingDocumentRecordsDocumentIdRoute,
  }

const ApiModelingDocumentRecordsRouteWithChildren =
  ApiModelingDocumentRecordsRoute._addFileChildren(
    ApiModelingDocumentRecordsRouteChildren,
  )

interface ApiModelingWorkspacesRouteChildren {
  ApiModelingWorkspacesWorkspaceIdRoute: typeof ApiModelingWorkspacesWorkspaceIdRoute
}

const ApiModelingWorkspacesRouteChildren: ApiModelingWorkspacesRouteChildren = {
  ApiModelingWorkspacesWorkspaceIdRoute: ApiModelingWorkspacesWorkspaceIdRoute,
}

const ApiModelingWorkspacesRouteWithChildren =
  ApiModelingWorkspacesRoute._addFileChildren(
    ApiModelingWorkspacesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiAgentHistoryRoute: ApiAgentHistoryRoute,
  ApiModelingDocumentRecordsRoute: ApiModelingDocumentRecordsRouteWithChildren,
  ApiModelingDocumentsRoute: ApiModelingDocumentsRoute,
  ApiModelingWorkspacesRoute: ApiModelingWorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
